//
// GlobalDefs.hpp
//
//  Created on: Dec 16, 2024
//  Author: Maksim Sushkov
//

#ifndef SOURCES_CORE_GLOBALHANDLEREVENTS_GLOBALDEFS_HPP_
#define SOURCES_CORE_GLOBALHANDLEREVENTS_GLOBALDEFS_HPP_

#include <string>
#include <map>

enum class HandlersFuncKeys {
    SWITCH_LANG,
    QUIT_APP,
    CONNECT,
    DISCONNECT,
    SELECT_STM32,
    SELECT_ESP32,
    SEARCH_FILE_STM32,
    SEARCH_FILE_ESP32,
    UPLOAD_FIRMWARE,
};

#endif // SOURCES_CORE_GLOBALHANDLEREVENTS_GLOBALDEFS_HPP_